credentials:
  usernames:
    Harshit Harsh:
      email: hharsh0599@gmail.com
      name: Harshit Harsh
      password: "(Harsh@99)" # To be replaced with hashed password

cookie:
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
    - hharsh0599@gmail.com
      hashed_passwords = stauth.Hasher(['(Harsh@99)]).generate()
